[package]
name = "gromnie"
version = "0.1.0"
edition = "2021"

[lib]
name = "libgromnie"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
byteorder = "1.5.0"
clap = "4.5.2"
deku = "0.16.0"
tokio = { version = "1.36.0", features = ["full"] }
