[package]
name = "gromnie"
version = "0.1.0"
edition = "2021"

[lib]
name = "libgromnie"
path = "src/lib/lib.rs"

[[bin]]
name = "check"
path = "src/bin/check.rs"

[dependencies]
deku = "0.16.0"
tokio = { version = "1.36.0", features = ["full"] }
