[package]
name = "gromnie"
version = "0.1.0"
edition = "2021"
authors = ["Bryce Mecum <petridish@gmail.com"]

readme = "README.md"
description = "Asheron's Call client test"
repository = "https://github.com/amoeba/gromnie.git"

keywords = []
categories = []

license = "Apache-2.0"

[lib]
name = "gromnie"
path = "src/lib.rs"

[[bin]]
name = "gromnie"
path = "src/bin/gromnie.rs"

[dependencies]
acprotocol = { path = "../asheron-rs/crates/acprotocol" }
bitflags = "2.6"
byteorder = "1.5.0"
chrono = "0.4"
clap = { version = "4.5.2", features = ["derive"] }
rand = "0.8"
rand_isaac = "0.3"
strum_macros = "0.26.1"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
