[package]
name = "gromnie"
version = "0.1.0"
edition = "2021"
authors = ["Bryce Mecum <petridish@gmail.com"]

readme = "README.md"
description = "Asheron's Call client test"
repository = "https://github.com/amoeba/gromnie.git"

keywords = []
categories = []

license = "Apache-2.0"

[lib]
name = "gromnie"
path = "src/lib.rs"

[[bin]]
name = "tui"
path = "src/bin/tui.rs"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[[bin]]
name = "discord-bot"
path = "src/bin/discord-bot.rs"

[[bin]]
name = "load-tester"
path = "src/bin/load-tester.rs"

[dependencies]
acprotocol = { git = "https://github.com/amoeba/asheron-rs" , rev = "a165e6ca82dd913281cb6280538ee5ab3bd1ef4b"}
bitflags = "2.6"
byteorder = "1.5.0"
chrono = "0.4"
clap = { version = "4.5.2", features = ["derive"] }
rand = "0.8"
rand_isaac = "0.3"
strum_macros = "0.26.1"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ratatui = { version = "0.29", features = ["serde"] }
crossterm = "0.28"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
directories = "5.0"
serenity = { version = "0.12", features = ["client", "gateway", "http", "utils"] }

[dev-dependencies]
